# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://brandoncaples.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Graphic & Web Designer, WordPress, SEO | Brandon Caples
  avatar: rocketship.png
  gravatar: # Email MD5 hash
  description: "I'm a WordPress and Ruby web developer with marketing, SEO, and design experience." # used by search engines

  # Header and footer text
  header_title: Brandon Caples
  header_text: >
     <h1>Graphic & Web Designer</h1>
  header_text_feature_image:
  footer_text: >
   Also check out <a href="https://www.capleswebdesign.com/">Caples Web Design</a>

  # Icons
  rss: false
  email_address: "brandoncaples@gmail.com"
  behance: # "brandon4abd"
  bitbucket:
  dribbble: # "brandoncaples"
  facebook: "bcaples"
  flickr:
  github: "capncapes"
  instagram:
  linkedin: "https://www.linkedin.com/in/brandoncaples"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: # "https://stackexchange.com/users/9627195/brandon"
  steam:
  tumblr:
  twitter: "capncapes"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-90007104-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Montserrat:500|Stoke&display=swap"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed

plugins: [jekyll-paginate]

# CONVERSION
excerpt_separator: ""